### ISSUE TITLE
React Native version mismatch

### ISSUE THREAD

**Issue by hooshyr** [viromedia/ViroARSampleApp#11]
`npm start`
after runnign when i open ViroMedia Testbed and enter ip i get this error
![image](https://user-images.githubusercontent.com/21290327/51535650-54cd2380-1e5e-11e9-8334-83bb795d28ff.png)

**Comment by dam00n** [comment]
You need to update your React Native version to 57.7 as ViroReact 2.13 is now compatible with that version. See release notes and upgrade instructions here -> https://docs.viromedia.com/docs/releases
