### ISSUE TITLE
ViroSampleApp Xcode Building issue

### ISSUE THREAD

**Issue by Polaris00418** [viromedia/ViroARSampleApp#2]
Hi viro friends!!
I have faced another error when building the xcode porject of virosampleapp.
mainly it was associated with "OBJC_CLASS$_VRTBundleURLProvider", referenced from:
objc-class-ref in AppDelegate.o
here islog of what i am suffering now.

ld: warning: ignoring file /Users/KHC/ViroSample/node_modules/react-viro/ios/dist/lib/libViroReact.a, missing required architecture x86_64 in file /Users/KHC/ViroSample/node_modules/react-viro/ios/dist/lib/libViroReact.a (2 slices)
ld: warning: ignoring file /Users/KHC/ViroSample/node_modules/react-viro/ios/dist/ViroRenderer/ViroKit.framework/ViroKit, missing required architecture x86_64 in file /Users/KHC/ViroSample/node_modules/react-viro/ios/dist/ViroRenderer/ViroKit.framework/ViroKit (2 slices)
Undefined symbols for architecture x86_64:
"OBJC_CLASS$_VRTBundleURLProvider", referenced from:
objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

thanks in advance!!!
![1](https://user-images.githubusercontent.com/35550887/35728709-72fa7452-07da-11e8-80d0-d74764ee180e.PNG)

i have uploaded the issued source project where i have been suffering xcode building erros;(
https://drive.google.com/open?id=1cLGsi-VzOvV5sKMORiQJUAc8y_xNXcsL

**Comment by achuvm** [comment]
Hi @Polaris00418,

Below is a copy of the answer I gave you on this question: https://github.com/viromedia/viro/issues/87#issuecomment-362658570

It looks like you're trying to build your app for the iOS Simulator (x86_64), we don't support the iOS Simulator, so you'll need to run it on an actual iOS device (iPhone/iPad).

I downloaded your project and was able to run it on my iPhone 6S, except I had to change 1 setting in the project file, I had to set "Enable Bitcode" to "No", see the screenshot below for my project setup:

<img width="956" alt="screen shot 2018-02-02 at 9 57 54 am" src="https://user-images.githubusercontent.com/21074927/35748047-7d28c2fe-0801-11e8-81ef-bd3a8b0dc18f.png">

Let me know if that works for you!

**Comment by achuvm** [comment]
Closing this issue in favor of: https://github.com/viromedia/viro/issues/159#issuecomment-362722584
