### ISSUE TITLE
error after fresh install

### ISSUE THREAD

**Issue by robertjuh** [viromedia/ViroARSampleApp#6]
> ``0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\tools\\NPMnodejs\\node.exe',
> 1 verbose cli   'C:\\tools\\NPMnodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'start' ]
> 2 info using npm@5.6.0
> 3 info using node@v10.0.0
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info lifecycle ViroSampleAR@0.0.1~prestart: ViroSampleAR@0.0.1
> 6 info lifecycle ViroSampleAR@0.0.1~start: ViroSampleAR@0.0.1
> 7 verbose lifecycle ViroSampleAR@0.0.1~start: unsafe-perm in lifecycle true
> 8 verbose lifecycle ViroSampleAR@0.0.1~start: PATH: C:\tools\NPMnodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\robert\viroGitClonetest\ViroARSampleApp\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\tools\python2\;C:\tools\python2\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\SlikSvn\bin;C:\Program Files\TortoiseSVN\bin;C:\Develop\Tools\sqlplus;C:\Program Files\Java\jdk1.8.0_151\bin;C:\Develop\Tools\apache-maven-3.5.0\bin;C:\Program Files (x86)\WinMerge;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Paragon Software\Hard Disk Manager 15 Premium\bluescrn\;C:\Program Files (x86)\Yarn\bin;C:\Program Files\Git\cmd;C:\Windows\yarn\bin;C:\ProgramData\chocolatey\bin;C:\tools\NPMnodejs\;"C:\Users\robert\AppData\Local\Microsoft\WindowsApps; C:\Users\robert\AppData\Local\Android\Sdk";C:\Users\robert\AppData\Local\Android\Sdk;C:\Users\robert\AppData\Local\Android\Sdk\platform-tools;C:\Program Files (x86)\Yarn\bin;C:\Users\robert\AppData\Roaming\npm
> 9 verbose lifecycle ViroSampleAR@0.0.1~start: CWD: C:\Users\robert\viroGitClonetest\ViroARSampleApp
> 10 silly lifecycle ViroSampleAR@0.0.1~start: Args: [ '/d /s /c',
> 10 silly lifecycle   'node node_modules/react-native/local-cli/cli.js start' ]
> 11 silly lifecycle ViroSampleAR@0.0.1~start: Returned: code: 11  signal: null
> 12 info lifecycle ViroSampleAR@0.0.1~start: Failed to exec start script
> 13 verbose stack Error: ViroSampleAR@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
> 13 verbose stack Exit status 11
> 13 verbose stack     at EventEmitter.<anonymous> (C:\tools\NPMnodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
> 13 verbose stack     at EventEmitter.emit (events.js:182:13)
> 13 verbose stack     at ChildProcess.<anonymous> (C:\tools\NPMnodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:182:13)
> 13 verbose stack     at maybeClose (internal/child_process.js:947:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:236:5)
> 14 verbose pkgid ViroSampleAR@0.0.1
> 15 verbose cwd C:\Users\robert\viroGitClonetest\ViroARSampleApp
> 16 verbose Windows_NT 10.0.16299
> 17 verbose argv "C:\\tools\\NPMnodejs\\node.exe" "C:\\tools\\NPMnodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
> 18 verbose node v10.0.0
> 19 verbose npm  v5.6.0
> 20 error code ELIFECYCLE
> 21 error errno 11
> 22 error ViroSampleAR@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
> 22 error Exit status 11
> 23 error Failed at the ViroSampleAR@0.0.1 start script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 11, true ]
> 

and my package.json:
(i already removed the IOS auto start thing)
```

{
  "name": "ViroSampleAR",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "eslint": "4.19.1",
    "react": "16.3.1",
    "react-native": "0.55.1",
    "react-viro": "2.6.0"
  },
  "devDependencies": {
    "babel-jest": "21.2.0",
    "babel-preset-react-native": "4.0.0",
    "jest": "21.2.1",
    "react-test-renderer": "16.0.0-beta.5"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

**Comment by VikAdvani** [comment]
Hi @robertjuh, this seems like a React-Native error, this issue seems similar: https://github.com/facebook/react-native/issues/11811

You can try deleting your node_modules directory and running npm install again. Then doing npm start and see if that fixes it. 

If that doesn't work try creating a new React Native project only(not Viro) and see if that works. If that breaks, then that confirms it's a React Native issue and not Viro. If it works, then it's something the Viro scripts are doing. 

Let me know if the above helps or if you are still running into issues. Thanks!

**Comment by robertjuh** [comment]
Yea thanks that worked :) 👍
