### ISSUE TITLE
Stucked on tracking to initialize

### ISSUE THREAD

**Issue by bilicio** [viromedia/ViroARSampleApp#8]
Hi,

Doesn't matter which key i use, i always get Key missing or invalid. do you know why? 

thank you

**Comment by dam00n** [comment]
Did you input your API Key in the App.js file as shown below (replacing the X's with your API key)?

apiKey="XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"

**Comment by bilicio** [comment]
yes i have!

I already have one app working with old version.
On the old version the api key is located under sharedProps property.

Now im testing this new viro version with the api key located on ViroARSceneNavigator but it seams to be invalid or missing somehow all the time.

Im running the demo app ViroARSampleApp without testbed. I converted the app to run without it.

this is where i put the Api Key:
<ViroARSceneNavigator style={localStyles.arView} apiKey="XXXXXXXXX-5C02-48CB-9A8D-CC93BF9E2AA9"

When i open the app it stuck on black screen and a message comes telling my Api key is missin or invalid.

**Comment by dam00n** [comment]
I was able to get the project to work with your API key. Can you try creating a new project for this sample app? Perhaps a clean project will resolve your issue.

Also, we just updated a couple files so the sample works with the latest Viro platform version so you should pull the latest.

**Comment by bilicio** [comment]
Hi dam00n, 

 Im using the ViroARSampleApp. maybe are something in it preventing me to use it with the key. so i create a new project with plain https://github.com/viromedia/viro (viro react) and it works right away. it is a mistery. but anyway thank you for help me out. if you want my project i can send to you for debug purposes. :)
